# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'distance_calc_tool.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 794)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.load_csv_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_csv_button.setGeometry(QtCore.QRect(30, 10, 133, 23))
        self.load_csv_button.setObjectName("load_csv_button")
        self.csv_filepath_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.csv_filepath_lineEdit.setGeometry(QtCore.QRect(170, 10, 594, 20))
        self.csv_filepath_lineEdit.setReadOnly(False)
        self.csv_filepath_lineEdit.setObjectName("csv_filepath_lineEdit")
        self.run_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_button.setGeometry(QtCore.QRect(620, 220, 133, 23))
        self.run_button.setObjectName("run_button")
        self.latitude_input_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.latitude_input_1.setEnabled(False)
        self.latitude_input_1.setGeometry(QtCore.QRect(170, 150, 281, 20))
        self.latitude_input_1.setObjectName("latitude_input_1")
        self.longitude_input_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.longitude_input_1.setEnabled(False)
        self.longitude_input_1.setGeometry(QtCore.QRect(470, 150, 291, 20))
        self.longitude_input_1.setObjectName("longitude_input_1")
        self.lat_label = QtWidgets.QLabel(self.centralwidget)
        self.lat_label.setGeometry(QtCore.QRect(290, 130, 47, 13))
        self.lat_label.setObjectName("lat_label")
        self.lon_label = QtWidgets.QLabel(self.centralwidget)
        self.lon_label.setGeometry(QtCore.QRect(590, 130, 61, 16))
        self.lon_label.setObjectName("lon_label")
        self.txt = QtWidgets.QTextEdit(self.centralwidget)
        self.txt.setGeometry(QtCore.QRect(30, 260, 731, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt.sizePolicy().hasHeightForWidth())
        self.txt.setSizePolicy(sizePolicy)
        self.txt.setAutoFillBackground(False)
        self.txt.setReadOnly(True)
        self.txt.setObjectName("txt")
        self.output_csv_button = QtWidgets.QPushButton(self.centralwidget)
        self.output_csv_button.setGeometry(QtCore.QRect(30, 50, 133, 23))
        self.output_csv_button.setObjectName("output_csv_button")
        self.output_filepath_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.output_filepath_lineEdit.setGeometry(QtCore.QRect(170, 50, 594, 20))
        self.output_filepath_lineEdit.setObjectName("output_filepath_lineEdit")
        self.use_fields_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.use_fields_checkbox.setGeometry(QtCore.QRect(30, 110, 133, 17))
        self.use_fields_checkbox.setChecked(False)
        self.use_fields_checkbox.setObjectName("use_fields_checkbox")
        self.latitude_input_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.latitude_input_2.setEnabled(False)
        self.latitude_input_2.setGeometry(QtCore.QRect(170, 180, 281, 20))
        self.latitude_input_2.setObjectName("latitude_input_2")
        self.longitude_input_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.longitude_input_2.setEnabled(False)
        self.longitude_input_2.setGeometry(QtCore.QRect(470, 180, 291, 20))
        self.longitude_input_2.setObjectName("longitude_input_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 150, 81, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 180, 71, 20))
        self.label_2.setObjectName("label_2")
        self.speed_input = QtWidgets.QLineEdit(self.centralwidget)
        self.speed_input.setEnabled(False)
        self.speed_input.setGeometry(QtCore.QRect(340, 220, 111, 22))
        self.speed_input.setObjectName("speed_input")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(174, 220, 141, 20))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculate distance"))
        self.load_csv_button.setText(_translate("MainWindow", "Load CSV"))
        self.run_button.setText(_translate("MainWindow", "Run"))
        self.lat_label.setText(_translate("MainWindow", "Latitude"))
        self.lon_label.setText(_translate("MainWindow", "Longitude"))
        self.output_csv_button.setText(_translate("MainWindow", "Output CSV"))
        self.use_fields_checkbox.setText(_translate("MainWindow", "manual input"))
        self.label.setText(_translate("MainWindow", "Start point"))
        self.label_2.setText(_translate("MainWindow", "End point"))
        self.label_3.setText(_translate("MainWindow", "Speed -knots (optional)"))

